<a href="https://colab.research.google.com/github/Mansi-3s/Creditt_wise_loan/blob/main/RNN_architectu_sentiment_analy%2CIMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### RNN Architecture_Sentimental Analysis on IMDB dataset

### Steps (Flow):


1.   Load Dataset
2.   Text pre-processing
3.   Tensor, create Dtasets, DataLoader
4.   Build RNN
5.   Train RNN
6.   Evaluate RNN
7.   Then we take new review(which is not available on IMDB) then pass through in RNN and check it's sentiment is either POSITVE OR NEGATIVE.

In [151]:
import pandas as pd
#load
df = pd.read_csv('/content/IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [152]:
df.shape

(50000, 2)

In [153]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [154]:
df.drop_duplicates(inplace=True)

In [155]:
df.shape

(49582, 2)

### Preprocessing:

1.  convert to LowerCase. [Poaitive == positive == POSITIVE]
2.  Remove urls (links).
3.  Remove HTML tags.
4.  Remove Punctuations.
5.  Remove Stopwords. (a, an, the, is, for etc)
6.  Perform Stemming.
7.  Encode Sentiments.(target values)
8.  Vectorization [convert txt into numbers] by TF-IDF

In [156]:
#1. convert lowercase
df["review"] = df["review"].str.lower()

to remove URLs we use "re"

In [157]:
#eg:
import re
txt = "Manak is good boy, Manak"  #Manak => Manav
new  =re.sub("Manak","Manav",txt)
print(new)

Manav is good boy, Manav

In [158]:
import re
def remove_urls(text):
  text = re.sub(r"http\S+" , "", text)
  return text

df["review"] = df["review"].apply(remove_urls)

In [159]:
#3. Remove punctuations
def remove_punctuations(text):
    text  = re.sub(r"[^A-Za-z0-9\s]","", text)
    return text


df["review"] = df["review"].apply(remove_punctuations)

In [160]:
# 4. Remove HTML
def remove_html(text):
    text  = re.sub(r"<.*?>","", text)
    return text

df["review"] = df["review"].apply(remove_html)

In [161]:
# 5. Remove Stopwords (use nltk)
import nltk
nltk.download('punkt') #Sentence tokenize
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [162]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

#eg
sample = "I love python."
token = word_tokenize(sample)
print(token)

['I', 'love', 'python', '.']

In [163]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words("english"))

    filtered_words = []

    for word in tokens:
        if word.lower() not in stop_words:
            filtered_words.append(word)

    return " ".join(filtered_words)
df["review"] = df["review"].apply(remove_stopwords)

In [164]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [150]:
# 6. Stemming
from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []
    tokens = word_tokenize(text)

    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " " .join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [165]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [166]:
#7. Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df['sentiment'])
y = df["sentiment"]

In [167]:
y #[+ve = 1, -ve = 0]

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [168]:
#8 . Vectorization

from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=5000)
x = tf.fit_transform(df["review"])

In [169]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3891434 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3093)	0.023496998856521435
  (0, 3673)	0.08377295536365317
  (0, 2796)	0.07294182261763837
  (0, 4823)	0.0857307833982265
  (0, 3143)	0.4938946518874717
  (0, 1505)	0.12720363218525832
  (0, 4990)	0.06031555687076218
  (0, 2149)	0.0923282546617867
  (0, 3689)	0.0959482381060147
  (0, 1550)	0.06383107946735145
  (0, 2025)	0.06393043510099257
  (0, 2773)	0.08465848577933201
  (0, 557)	0.06812538749399723
  (0, 1735)	0.07086132225332989
  (0, 4449)	0.043133245302294655
  (0, 4235)	0.18477035004383593
  (0, 3811)	0.042380479876072776
  (0, 4753)	0.2615860469689601
  (0, 3897)	0.05258795976086102
  (0, 4935)	0.06549777668665845
  (0, 1919)	0.04195782944447555
  (0, 4604)	0.08099527060884129
  (0, 3953)	0.13493179698734273
  (0, 3451)	0.08748052736980606
  (0, 1373)	0.08139631285015804
  :	:
  (49581, 1646)	0.11286691681970248
  (49581, 2177)	0.09659205837358956
  (49581, 4602)	0.10921530898812264
  (49581, 743)	0.13006812562695924
  (49581, 3792)	0.13019853748945864
  (49581, 2478)	0.13148321193059173
  (49581, 4663)	0.12319635372435526
  (49581, 2548)	0.11077861983510061
  (49581, 1574)	0.12680155864924406
  (49581, 366)	0.1393558912559679
  (49581, 2034)	0.14800654090904644
  (49581, 2976)	0.1378694080875155
  (49581, 2256)	0.13034592262564235
  (49581, 2237)	0.1974102203505001
  (49581, 1648)	0.12444121776863279
  (49581, 309)	0.13245284095526372
  (49581, 4580)	0.18713816743505152
  (49581, 2468)	0.2140534702444387
  (49581, 3623)	0.18126041620101888
  (49581, 1506)	0.14394689029009136
  (49581, 638)	0.17229599198851564
  (49581, 3003)	0.1918424122106333
  (49581, 750)	0.2010470238356412
  (49581, 1933)	0.18420189596744713
  (49581, 3621)	0.1773214747848907

### Dataset and DataLoader

In [170]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [171]:
X_train.shape

(39665, 5000)

In [172]:
X_test.shape

(9917, 5000)

In [173]:
from torch.utils.data import TensorDataset, DataLoader
import torch

In [174]:
X_train # its type is Sparse, we cannot use sparse directly so, first convert it into numpy.

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3114621 stored elements and shape (39665, 5000)>

In [175]:
X_test = X_test.toarray()
X_train = X_train.toarray()

In [176]:
train_set = TensorDataset(torch.from_numpy(X_train).float(), torch.from_numpy(y_train.to_numpy()).float())
test_set = TensorDataset(torch.from_numpy(X_test).float(), torch.from_numpy(y_test.to_numpy()).float())

In [177]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
test_loader = DataLoader(test_set, batch_size=64, shuffle=True)

### Build RNN

In [178]:
import torch.nn as nn
import torch.optim as optim

In [179]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0)
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [180]:
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

### Training the RNN

In [181]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction

        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.26489362120628357
epoch = 2/10 and loss = 0.28184059262275696
epoch = 3/10 and loss = 0.21277114748954773
epoch = 4/10 and loss = 0.16122400760650635
epoch = 5/10 and loss = 0.1691577285528183
epoch = 6/10 and loss = 0.23961320519447327
epoch = 7/10 and loss = 0.1384657770395279
epoch = 8/10 and loss = 0.2529294490814209
epoch = 9/10 and loss = 0.18343454599380493
epoch = 10/10 and loss = 0.33234620094299316

In [182]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 87.49621861450035